function summary = summarize_learning_curves(runRoot, diagnostics)
%SUMMARIZE_LEARNING_CURVES Summary table and figures for the
%primary-model learning curve.
%
% The positive network is the reported model. Combined and negative medians
% are carried alongside it so the supplement can be written without rerunning.

if nargin < 2, diagnostics = false; end
assert(nargin >= 1 && ~isempty(runRoot), ...
    'CPM:LearningCurveSummary:RunRootRequired', ...
    'Supply the learning-curve run directory.');
outputPath = fullfile(runRoot, 'output');
rawCsv = fullfile(outputPath, 'primary_learning_curve_raw_results.csv');
summaryCsv = fullfile(outputPath, 'primary_learning_curve_summary.csv');
assert(isfile(rawCsv), 'CPM:PrimaryCurveSummary:MissingRaw', ...
    'Missing raw results: %s', rawCsv);

% Table 1 order.
OUTCOMES = ["GDE", "MEQ30", "VRS", "OBN", "BDE", "AED"];
PANEL_TITLES = containers.Map( ...
    {'GDE', 'MEQ30', 'VRS', 'OBN', 'BDE', 'AED'}, ...
    {'GDE (VAS Good Drug Effect)', 'MEQ30 Total Score', ...
     'VRS (Visionary Restructuralization)', ...
     'OBN (Oceanic Boundlessness)', 'BDE (VAS Bad Drug Effect)', ...
     'AED (Anxious Ego Dissolution)'});
raw = readtable(rawCsv, 'TextType', 'string');
expectedRepetitions = max(raw.Repetition);
groups = unique(raw(:, {'Outcome','SampleN'}), 'rows');
expectedRows = height(groups) * expectedRepetitions;
assert(height(raw) == expectedRows, 'CPM:PrimaryCurveSummary:RawRows', ...
    'Expected %d raw rows; found %d.', expectedRows, height(raw));
assert(all(isfinite(raw{:, 6:end}), 'all'), ...
    'CPM:PrimaryCurveSummary:NonfiniteRaw', ...
    'The raw result table contains NaN or Inf values.');
assert(all(raw.ConnectomeForm == "LSD_difference") && ...
    all(raw.CovariateSetting == "With covariates"), ...
    'CPM:PrimaryCurveSummary:UnexpectedCondition', ...
    'The raw file must contain only the primary model condition.');

summary = empty_summary_table();
for outcome = OUTCOMES
    outcomeRows = raw(raw.Outcome == outcome, :);
    assert(~isempty(outcomeRows), ...
        'CPM:PrimaryCurveSummary:MissingOutcome', ...
        'No rows found for %s.', outcome);
    behaviorForms = unique(outcomeRows.BehaviorFormUsed);
    assert(isscalar(behaviorForms), ...
        'CPM:PrimaryCurveSummary:BehaviorForm', ...
        '%s used more than one behavior form.', outcome);
    for sampleN = unique(outcomeRows.SampleN, 'sorted')'
        current = outcomeRows(outcomeRows.SampleN == sampleN, :);
        assert(height(current) == expectedRepetitions && ...
            numel(unique(current.Repetition)) == expectedRepetitions, ...
            'CPM:PrimaryCurveSummary:Repetitions', ...
            '%s/N=%d does not contain the configured repetitions.', ...
            outcome, sampleN);
        positiveLimits = prctile(current.RPositive, [2.5 97.5]);
        summary(end+1, :) = {outcome, behaviorForms, sampleN, ...
            current.Study1N(1), current.Study2N(1), current.Study3N(1), ...
            height(current), ...
            median(current.RPositive), positiveLimits(1), ...
            positiveLimits(2), mean(current.RPositive), ...
            median(current.PPositive), sum(current.PPositive < 0.05), ...
            mean(current.PPositive < 0.05), ...
            median(current.MSEPositive), median(current.PMSEPositive), ...
            median(current.RCombined), median(current.PCombined), ...
            median(current.RNegative), ...
            median(current.PNegative)}; %#ok<AGROW>
    end
end

assert(height(summary) == height(groups), ...
    'CPM:PrimaryCurveSummary:SummaryRows', ...
    'Expected %d summary rows; found %d.', height(groups), height(summary));
write_table_atomic(summary, summaryCsv);
if diagnostics
    make_curve_figure(summary, 'r', outputPath, OUTCOMES, PANEL_TITLES);
    make_curve_figure(summary, 'detection', outputPath, OUTCOMES, PANEL_TITLES);
end
fprintf('Primary learning-curve summary created: %s (%d rows).\n', ...
    summaryCsv, height(summary));
end


function tableValue = empty_summary_table
variableNames = {'Outcome','BehaviorFormUsed','SampleN', ...
    'Study1N','Study2N','Study3N','CompletedRepetitions', ...
    'MedianRPositive','RPositiveP2_5','RPositiveP97_5','MeanRPositive', ...
    'MedianRawPPositive','RawPSignificantCount','RawPSignificantFraction', ...
    'MedianMSEPositive','MedianRawPMSEPositive', ...
    'MedianRCombined','MedianRawPCombined', ...
    'MedianRNegative','MedianRawPNegative'};
variableTypes = [repmat({'string'}, 1, 2), repmat({'double'}, 1, 18)];
tableValue = table('Size', [0 numel(variableNames)], ...
    'VariableTypes', variableTypes, 'VariableNames', variableNames);
end


function make_curve_figure(summary, figureType, outputPath, outcomes, ...
        panelTitles)
lineColor = [0.85 0.33 0.10];

% A single y-range across panels so the six dimensions stay comparable.
if strcmp(figureType, 'r')
    span = [min(summary.RPositiveP2_5), max(summary.RPositiveP97_5)];
    padding = 0.05 * diff(span);
    sharedYLimits = [floor((span(1) - padding) * 10) / 10, ...
        ceil((span(2) + padding) * 10) / 10];
else
    sharedYLimits = [0 1];
end

figureHandle = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100 100 1400 840]);
cleanup = onCleanup(@() close(figureHandle));
layout = tiledlayout(2, 3, 'TileSpacing', 'compact', 'Padding', 'compact');
% Reserve a bottom strip for the note so it cannot overlap the x-labels.
set(layout, 'OuterPosition', [0 0.06 1 0.94]);

for outcomeIndex = 1:numel(outcomes)
    outcome = outcomes(outcomeIndex);
    axisHandle = nexttile(layout);
    set(axisHandle, 'Color', 'white', 'XColor', 'black', ...
        'YColor', 'black', 'GridColor', [0.75 0.75 0.75], ...
        'GridAlpha', 0.45, 'FontSize', 9);
    hold(axisHandle, 'on');
    grid(axisHandle, 'on');

    current = sortrows(summary(summary.Outcome == outcome, :), 'SampleN');
    x = current.SampleN';
    if strcmp(figureType, 'r')
        lower = current.RPositiveP2_5';
        upper = current.RPositiveP97_5';
        fill(axisHandle, [x fliplr(x)], [lower fliplr(upper)], ...
            lineColor, 'FaceAlpha', 0.12, 'EdgeColor', 'none', ...
            'HandleVisibility', 'off');
        y = current.MedianRPositive;
    else
        y = current.RawPSignificantFraction;
    end
    plot(axisHandle, current.SampleN, y, 'Color', lineColor, ...
        'LineStyle', '-', 'LineWidth', 1.8, 'Marker', 'o', ...
        'MarkerSize', 4.5, 'MarkerFaceColor', 'white');

    title(axisHandle, panelTitles(char(outcome)), ...
        'FontWeight', 'bold', 'Color', 'black', 'FontSize', 10);
    xlabel(axisHandle, 'Participants included (N)', 'Color', 'black');
    xlim(axisHandle, [18 69]);
    xticks(axisHandle, [20 30 40 50 60 67]);
    ylim(axisHandle, sharedYLimits);
    if strcmp(figureType, 'r')
        yline(axisHandle, 0, ':', 'Color', [0.35 0.35 0.35], ...
            'HandleVisibility', 'off');
        ylabel(axisHandle, 'Median out-of-fold r', 'Color', 'black');
    else
        yline(axisHandle, 0.05, ':', 'Color', [0.35 0.35 0.35], ...
            'HandleVisibility', 'off');
        ylabel(axisHandle, 'Fraction with raw p < 0.05', 'Color', 'black');
    end
end

if strcmp(figureType, 'r')
    titleText = ['Internal-validation learning curves: positive ' ...
        'LSD-PCB difference model with covariates'];
    noteText = [ ...
        'Lines show medians over 100 nested study-stratified repetitions ' ...
        'of the primary model. Shading shows the 2.5th-97.5th percentile ' ...
        'range across repetitions (descriptive, not a confidence interval). ' ...
        'MEQ30 ends at its available N=48.'];
    baseName = 'primary_learning_curve_positive_r';
else
    titleText = ['Internal-validation learning curves: raw-p detection ' ...
        'frequency, positive LSD-PCB difference model with covariates'];
    noteText = [ ...
        'Each point is the fraction of 100 repetitions with raw ' ...
        'permutation p < 0.05 for the positive network of the primary ' ...
        'model. This is descriptive, not a prospective power ' ...
        'calculation. MEQ30 ends at N=48.'];
    baseName = 'primary_learning_curve_detection_frequency';
end

sgtitle(layout, titleText, 'FontWeight', 'bold', 'Color', 'black', ...
    'FontSize', 12);
annotation(figureHandle, 'textbox', [0.06 0.008 0.88 0.042], ...
    'String', noteText, 'EdgeColor', 'none', 'FontSize', 9, ...
    'Color', [0.25 0.25 0.25], 'Interpreter', 'none', ...
    'HorizontalAlignment', 'left', 'VerticalAlignment', 'bottom', ...
    'FitBoxToText', 'off');

exportgraphics(figureHandle, fullfile(outputPath, [baseName '.png']), ...
    'Resolution', 300);
exportgraphics(figureHandle, fullfile(outputPath, [baseName '.pdf']), ...
    'ContentType', 'vector');
clear cleanup
end


function write_table_atomic(tableValue, pathName)
temporary = [tempname(fileparts(pathName)) '.csv'];
writetable(tableValue, temporary);
[ok, message] = movefile(temporary, pathName, 'f');
assert(ok, 'CPM:PrimaryCurveSummary:WriteFailed', ...
    'Could not write %s: %s', pathName, message);
end
