function verify_network_interaction_statistics(outputPath, expectedIterations)
%VERIFY_NETWORK_INTERACTION_STATISTICS Recompute count inference from checkpoint.

if nargin < 1 || isempty(outputPath)
    scriptDir = fileparts([mfilename('fullpath') '.m']);
    repositoryRoot = fileparts(fileparts(scriptDir));
    outputPath = fullfile(repositoryRoot, 'outputs', 'network_interactions');
end
if nargin < 2 || isempty(expectedIterations), expectedIterations = 10000; end

loaded = load(fullfile(outputPath, 'network_interaction_checkpoint.mat'), ...
    'checkpoint');
pairs = readtable(fullfile(outputPath, 'network_pair_results.csv'), ...
    'TextType', 'string');
summary = readtable(fullfile(outputPath, 'outcome_summary.csv'), ...
    'TextType', 'string');
workbookPath = fullfile(outputPath, 'network_interaction_results.xlsx');
assert(isfile(workbookPath), ...
    'CPM:NetworkInteraction:VerificationWorkbookMissing', ...
    'Required XLSX workbook is missing.');

assert(height(pairs) == 108 && height(summary) == 3, ...
    'CPM:NetworkInteraction:VerificationShape', ...
    'Expected 108 pair rows and 3 summary rows.');
expectedMaskQ = local_bh(summary.TotalMaskPermutationP);
assert(max(abs(summary.TotalMaskFDRQ - expectedMaskQ)) < 1e-12 && ...
    isequal(summary.TotalMaskFDRSignificant, expectedMaskQ < 0.05), ...
    'CPM:NetworkInteraction:VerificationTotalMaskQ', ...
    'Whole-mask q-values do not match BH correction across three outcomes.');
assert(~any(ismember({'EmpiricalPermutationP', 'FDRQ'}, ...
    pairs.Properties.VariableNames)), ...
    'CPM:NetworkInteraction:DeprecatedRatioInference', ...
    'Deprecated fold-enrichment inference columns remain in the output.');

for outcomeIndex = 1:numel(loaded.checkpoint.outcomes)
    current = loaded.checkpoint.outcomes{outcomeIndex};
    counts = double(current.network_positive_counts);
    assert(size(counts, 1) == expectedIterations + 1, ...
        'CPM:NetworkInteraction:VerificationIterationCount', ...
        'Checkpoint iteration count does not match the requested run.');
    observed = counts(1, :)';
    nullCounts = counts(2:end, :);
    expectedP = (1 + sum(nullCounts >= observed', 1))' ...
        / (expectedIterations + 1);
    expectedQ = local_bh(expectedP);
    totals = sum(counts, 2);
    expectedTotalP = (1 + sum(totals(2:end) >= totals(1))) ...
        / (expectedIterations + 1);

    pairRows = pairs(pairs.Outcome == string(current.behavior), :);
    pairRows = sortrows(pairRows, 'PairIndex');
    summaryRow = summary(summary.Outcome == string(current.behavior), :);
    assert(height(pairRows) == 36 && height(summaryRow) == 1, ...
        'CPM:NetworkInteraction:VerificationOutcomeRows', ...
        'Outcome tables have an unexpected number of rows.');
    assert(isequal(pairRows.ObservedConsensusEdges, observed), ...
        'CPM:NetworkInteraction:VerificationObservedCounts', ...
        'Observed network-pair counts do not match the checkpoint.');
    assert(max(abs(pairRows.CountPermutationP - expectedP)) < 1e-12, ...
        'CPM:NetworkInteraction:VerificationPairP', ...
        'Raw-count pair p-values do not match the checkpoint.');
    assert(max(abs(pairRows.CountFDRQ - expectedQ)) < 1e-12, ...
        'CPM:NetworkInteraction:VerificationPairQ', ...
        'Raw-count pair q-values do not match independent BH correction.');
    assert(isequal(pairRows.CountFDRSignificant, expectedQ < 0.05), ...
        'CPM:NetworkInteraction:VerificationPairSignificance', ...
        'Raw-count FDR significance flags are inconsistent.');
    assert(abs(summaryRow.TotalMaskPermutationP - expectedTotalP) < 1e-12, ...
        'CPM:NetworkInteraction:VerificationTotalP', ...
        'Total-mask p-value does not match the checkpoint.');
    assert(summaryRow.ZeroEdgeNullMasks == sum(totals(2:end) == 0), ...
        'CPM:NetworkInteraction:VerificationZeroMasks', ...
        'Zero-edge null-mask count is inconsistent.');
end

workbookSheets = string(sheetnames(workbookPath));
assert(isequal(workbookSheets(:), ...
    ["Network Pairs"; "Outcome Summary"; "Parameters"]), ...
    'CPM:NetworkInteraction:VerificationWorkbookSheets', ...
    'Workbook sheets or sheet order are incorrect.');
workbookPairs = readtable(workbookPath, 'Sheet', 'Network Pairs', ...
    'TextType', 'string');
workbookSummary = readtable(workbookPath, 'Sheet', 'Outcome Summary', ...
    'TextType', 'string');
assert(height(workbookPairs) == 108 && height(workbookSummary) == 3, ...
    'CPM:NetworkInteraction:VerificationWorkbookRows', ...
    'Workbook table sizes are incorrect.');
assert(isequal(workbookPairs.ObservedConsensusEdges, ...
    pairs.ObservedConsensusEdges) && ...
    max(abs(workbookPairs.CountPermutationP - pairs.CountPermutationP)) < 1e-12 && ...
    max(abs(workbookPairs.CountFDRQ - pairs.CountFDRQ)) < 1e-12, ...
    'CPM:NetworkInteraction:VerificationWorkbookPairValues', ...
    'Workbook pair results do not match the canonical CSV.');
assert(max(abs(workbookSummary.TotalMaskPermutationP - ...
    summary.TotalMaskPermutationP)) < 1e-12, ...
    'CPM:NetworkInteraction:VerificationWorkbookSummaryValues', ...
    'Workbook total-mask p-values do not match the canonical CSV.');
assert(max(abs(workbookSummary.TotalMaskFDRQ - ...
    summary.TotalMaskFDRQ)) < 1e-12 && ...
    isequal(workbookSummary.TotalMaskFDRSignificant, ...
        summary.TotalMaskFDRSignificant), ...
    'CPM:NetworkInteraction:VerificationWorkbookSummaryQ', ...
    'Workbook total-mask q-values do not match the canonical CSV.');

fprintf(['PASS: raw-count pair inference, total-mask p/q-values, and XLSX ' ...
    'tables match the checkpoint/CSV sources.\n']);
end


function q = local_bh(p)
[sortedP, order] = sort(p(:), 'ascend');
m = numel(sortedP);
adjusted = sortedP .* m ./ (1:m)';
adjusted = flipud(cummin(flipud(adjusted)));
q = zeros(size(adjusted));
q(order) = min(adjusted, 1);
end
